FeelGreat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('FeelGreat_main/', include('FeelGreat_main.urls')),
    path('admin/', admin.site.urls),
]

FeelGreat_main/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import views


app_name = 'FeelGreat_main'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('userrecords/<int:user_id>/', views.users_recent_records, name='users_recent_records'),
    path('progress_page/', views.progress_summary, name='progress_page'),
    path('makerecord/<int:activity_id>/', views.record_activity, name='record_activity'),
    path('record_daily_activity/', views.record_daily_activity, name='record_daily_activity'),
    path('leader_board/', views.leader_board, name='leader_board'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

FeelGreat_main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from django.views import generic

from .models import ActivityLookup, ActivityRecord, UserProfile, UnitsOfMeasure
from .utils import get_differentials, convert_to_percent, get_plot, get_point_leaders, get_weight_loss_leaders,\
    get_frequency_leaders, get_streak_leaders, cumsum
from django.contrib.auth.models import User, auth
from django.contrib import messages


# Create your views here.
class IndexView(generic.ListView):
    template_name = "FeelGreat_main/index.html"
    context_object_name = 'high_scoring_activities'

    def get_queryset(self):
        """Return All activities"""
        return ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by('-point_value')


def index(request):
    high_scoring_activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by('-point_value')
    weigh_in_activity = ActivityLookup.objects.get(activity_name="Weigh In")
    context = {'high_scoring_activities': high_scoring_activities,
               'weigh_in_activity': weigh_in_activity}
    return render(request, "FeelGreat_main/index.html", context)


def record_activity(request, activity_id):
    if request.method == "POST":
        act = ActivityLookup.objects.get(pk=activity_id)
        value = float(request.POST[act.activity_name])
        points, _ = ActivityRecord.verify_points_input(request, activity_id)
        user = request.user
        if not user.is_authenticated:
            messages.info(request, "Please sign-in or register in order to track activity.")
            return render(request, 'FeelGreat_main/register.html')
        user_prof = UserProfile.objects.filter(user_name=user.username)[0]
        record = ActivityRecord.create(new_points=points, number_recorded=value,
                                       user=user, act_num=activity_id,)
        record.save()
        return users_recent_records(request, user_prof.user_number)
    else:
        try:
            act = ActivityLookup.objects.get(pk=activity_id)
        except ActivityLookup.DoesNotExist:
            raise Http404("Activity does not exist")
        return render(request, 'FeelGreat_main/record_activity.html',
                      {'activity': act})


def users_recent_records(request, user_id):
    try:
        current_user = UserProfile.objects.get(pk=user_id)
    except UserProfile.DoesNotExist:
        raise Http404("That User does not exist. \
                       Contact administrator for more help.")
    users_records = ActivityRecord.objects.filter(user_num=user_id)
    users_records = users_records.order_by('-record_date')
    context = {'current_user': current_user, 'users_records': users_records}
    return render(request, "FeelGreat_main/users_recent_records.html", context)

def progress_summary(request):
    if request.user.is_authenticated:
        weigh_in_act = ActivityLookup.objects.get(activity_name="Weigh In")
        weigh_in_records = ActivityRecord.objects.filter(user_num=request.user.id).filter(activity_num=weigh_in_act.activity_number)
        points_records = ActivityRecord.objects.filter(user_num=request.user.id)
        print("Length of reocrds list: {}".format(len(points_records)))
        if len(points_records)==0:
            print("not enough records")
            messages.info(request, "You do not have enough activities recorded. \
                                    Keep using the app and be sure to record activity.")
            high_scoring_activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by(
                '-point_value')
            weigh_in_activity = ActivityLookup.objects.get(activity_name="Weigh In")
            context = {'high_scoring_activities': high_scoring_activities,
                       'weigh_in_activity': weigh_in_activity}
            return render(request, "FeelGreat_main/index.html", context)
        context = {}
        # make the points plot
        points_records = points_records.order_by('record_date')
        dates = [x.record_date for x in points_records]
        cum_points = [y.points for y in points_records]
        cum_points = cumsum(cum_points)
        print(dates)
        print(cum_points)
        points_plot = get_plot(dates, cum_points, plot_title="Cumulative Sum of Points",
                               y_label="Points")
        context['points_plot'] = points_plot
        print(context)
        # make the weight based plots
        if len(weigh_in_records) > 1:
            weigh_in_records = weigh_in_records.order_by('record_date')
            x = [x.record_date for x in weigh_in_records]
            y = [y.number_recorded for y in weigh_in_records]
            diffs = get_differentials(y)
            perc = convert_to_percent(y)
            diff_plot = get_plot(x, diffs, plot_title="Change in Weight",
                                 y_label="Weight Change (pounds)")
            percent_plot = get_plot(x, perc, plot_title="Percent Weight Lost",
                                    y_label="Percent of original weight")
            context['percent_plot'] = percent_plot
            context['diff_plot'] = diff_plot
        else:
            print("not enough records")
            messages.info(request, "You do not have enough Weigh In activities recorded to show weight \
                                    loss progress. Keep using the app and be sure to weigh in.")
        return render(request, "FeelGreat_main/progress_page.html", context)

    else:
        print("user was not logged in")
        messages.info(request, "You need to log in before \
                                recording and tracking activity.")
        return render(request, "FeelGreat_main/login.html")



def record_daily_activity(request):
    activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.WEEKLY).exclude(value_type=UnitsOfMeasure.POUNDS).exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL)
    daily_act = ActivityLookup.get_daily_activity()
    checklist_activities = activities.filter(value_type=UnitsOfMeasure.DAILY)
    quantity_activities = activities.exclude(value_type=UnitsOfMeasure.DAILY)

    checklist_strings = [a.activity_name for a in checklist_activities]
    quantity_strings = [a.activity_name for a in quantity_activities]

    checklist_stuff = zip(checklist_activities, checklist_strings)
    quantity_stuff = zip(quantity_activities, quantity_strings)

    if request.method == "POST":
        if request.user.is_authenticated:
            user_prof = UserProfile.objects.get(user_number=request.user.id)
            qs_4_dailyact = ActivityLookup.objects.filter(pk=daily_act.activity_number)
            activities = activities.union(qs_4_dailyact)  # append daily act queryset
            for act in activities:
                activity_id = ActivityLookup.objects.get(activity_name=act.activity_name).activity_number
                points, value = ActivityRecord.verify_points_input(request,
                                                                   activity_id)
                if points == 0 and value == 0:
                    continue  # Fields were blank so no record needs to be made
                record = ActivityRecord.create(new_points=points,
                                               number_recorded=value,
                                               user=request.user,
                                               act_num=activity_id,)
                record.save()
            return users_recent_records(request, user_prof.user_number)
        else:
            messages.info(request, "You need to log in before \
                                    recording activity.")
            return render(request, "FeelGreat_main/login.html")
    else:
        if daily_act.activity_name == "Weigh In":
            weigh_in_bool = True
        else:
            weigh_in_bool = False
        context = {'checklist_stuff': checklist_stuff,
                   'quantity_stuff': quantity_stuff,
                   'daily_activity': daily_act,
                   'daily_activity_string': daily_act.activity_name,
                   'weigh_in': weigh_in_bool
                   }
        return render(request, "FeelGreat_main/make_daily_record.html",
                      context)


def leader_board(request):
    if request.method == 'POST':
        comparison = request.POST['comparison']
        if comparison == "points":
            leader_list = get_point_leaders()  # this shows all users
            units = "points"
        elif comparison == "weight loss":
            leader_list = get_weight_loss_leaders()
            units = "% of starting weight"
        elif comparison == "frequency":
            leader_list = get_frequency_leaders()
            units = " the number of days with records"
        elif comparison == "streak":
            leader_list = get_streak_leaders()
            units = "days in a row"
        context = {"leaders": leader_list, "title": comparison, "units": units}
        return render(request, "FeelGreat_main/leader_board.html", context)

    else:
        return render(request, "FeelGreat_main/leader_board.html")

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'home.html')
        else:
            messages.info(request, "Invalid Username or Password")
            return render(request, "FeelGreat_main/login.html")
    else:
        return render(request, "FeelGreat_main/login.html")


def logout(request):
    auth.logout(request)
    return redirect("/FeelGreat_main/login/")


def register(request):

FeelGreat_main/templates/FeelGreat_main/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
<p>List of Activities</p>
    {% if high_scoring_activities %}
        <ul>
        {% for activity in high_scoring_activities %}
            <li><a href="{% url 'FeelGreat_main:record_activity' activity.activity_number %}">{{ activity.activity_name }}</a></li>
        {% endfor %}
            {% if weigh_in_activity %}
                <li><a href="{% url 'FeelGreat_main:record_activity' weigh_in_activity.activity_number %}">{{ weigh_in_activity.activity_name }}</a></li>
            {% endif %}
        </ul>
    {% else %}
        <p>No Activities are available.</p>
    {% endif %}
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/leader_board.html
<!-- templates/leader_board.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if leaders %}
    <h2>Current {{title}} leaders:</h2>
    <h4>(reported as {{units}})</h4>
    {% for l in leaders %}
      <p>{{l.0}}  ..........  {{l.1}}</p>
    {% endfor %}
  {% else %}
    <p>Enter criteria for leader board to appear</p>
  {% endif %}
  <br>
  <form method="POST" action="">
    {% csrf_token %}
    <label for="comparison">next comparison:</label>
    <select id="comparison" name="comparison">
      <option value="points">Points</option>
      <option value="weight loss">Weight Lost</option>
      <option value="frequency">Frequency</option>
      <option value="streak">Streak</option>
    </select>
    <input type="submit" />
  </form>
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/login.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Log In</h2>

<form method="POST" action="">
  {% csrf_token %}
  <p>Username: </p><br>
  <input type="text" name="username" />
  <p>Password: </p><br>
  <input type="password" name="password" /><br>
  <button type="Submit">Log In</button>
</form>
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/make_daily_record.html
{% extends 'base.html' %}

{% block title %}Daily Record{% endblock %}

{% block content %}
<h2> Today's Activity Entry </h2>
<form method="POST" action="">
    {% csrf_token %}

    <ul class="daily_list">
        {% for acty, acty_string in quantity_stuff %}
            <li><label for="{{acty_string}}" title="{{acty.act_description}}">{{acty.activity_name}}: </label>
            <input type="number" id="{{acty_string}}" name="{{acty_string}}">
            <label for="{{acty_string}}">{{acty.value_type}}s per day.</label>
            </li>
        {% endfor %}
    </ul>
    <ul class="daily_list">
        {% for act, act_string in checklist_stuff %}
            <li><input type="checkbox" id="{{act_string}}" name="{{act_string}}" >
            <label for="{{act_string}}" title="{{act.act_description}}">{{act.activity_name}}</label></li>
        {% endfor %}
        {% if weigh_in %}
            <li><input type="number" id="Weigh In" name="Weigh In" >
             <label for="Weigh In" title="{{daily_activity.act_description}}">{{daily_activity.activity_name}}</label></li>
        {% else %}
            <li><input type="checkbox" id="{{daily_activity_string}}" name="{{daily_activity_string}}" >
             <label for="{{daily_activity_string}}" title="{{daily_activity.act_description}}">{{daily_activity.activity_name}}</label></li>
        {% endif %}
    </ul>
    <input type="submit" />
</form>

{% endblock %}

FeelGreat_main/templates/FeelGreat_main/progress_page.html
{% extends 'base.html' %}

{% block title %}Progress Page{% endblock %}

{% block content %}
    <h3>Here is a Plot of your weight</h3>
    <div name="Plot Area">
        {% if points_plot %}
        <img src="data:image.png;base64, {{points_plot|safe}}" >
        {% else %}
        <p> Sorry, something went wrong with creating your points plot.
            Please check back later or contact the website maintainer.</p>
        {% endif %}
        <br>
        <br>
        {% if percent_plot %}
        <img src="data:image.png;base64, {{percent_plot|safe}}" >
        {% else %}
        <p> Sorry, something went wrong with creating your percent plot.
            Please check back later or contact the website maintainer.</p>
        {% endif %}
        <br>
        <br>
        {% if diff_plot %}
        <img src="data:image.png;base64, {{diff_plot|safe}}" >
        {% else %}
        <p> Sorry, something went wrong with creating your weight difference plot.
            Please check back later or contact the website maintainer.</p>
        {% endif %}
    </div>
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/record_activity.html
{% extends 'base.html' %}

{% block title %}Activity Entry{% endblock %}

{% block content %}
    <div class="activityinfo">
        <h3>{{ activity.activity_name }}</h3>
        <p> This activity is worth {{ activity.point_value }} point(s) per {{ activity.value_type }}.</p>
        {% if activity.daily_point_limit == 0 %}
            <p>There is no daily point limit for this activity.</p>
        {% else %}
            <p>The daily point limit is {{ activity.daily_point_limit }}.</p>
        {% endif %}
    </div>
    <br>
    <div class="activityinfo">
        <p>
            {{activity.act_description}}
        </p>
    </div>
    <br>
    <div class="activityentry">
        <form method="POST" action="">
            {% csrf_token %}
            <input type="number" name="{{activity.activity_name}}"/>
            <button type="submit"> Record </button>
        </form>
    </div>
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/register.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Register Here</h1>
{% for mes in messages %}
    <h3>{{ mes }}</h3>
{% endfor %}
<form method="POST" action="">
    {% csrf_token %}
    <p>User Name:</p>
    <input type="text" name="username" placeholder="Username"/>
    <br>
    <p>Password:</p>
    <input type="password" name="password" placeholder="password"/>
    <p>Password again:</p>
    <input type="password" name="password2" placeholder="same password"/>
    <br>
    <p>First Name:</p>
    <input type="text" name="firstname" placeholder="First Name" />
    <br>
    <p>Last Name:</p>
    <input type="text" name="lastname"  placeholder="Last Name"/>
    <br>
    <p>E-mail:</p>
    <input type="email" name="email" placeholder="E-mail"/>
    <br>
    <p>Birthdate</p>
    <input type="date" name="birthdate"/>
    <input type="submit" />
</form>
{% endblock %}

FeelGreat_main/templates/FeelGreat_main/users_recent_records.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <p> Here is a list of your most recent entries.</p>
    <table class='recordtable'>
        <tr>
            <th> Date </th>
            <th> Activity </th>
            <th> Units Recorded </th>
            <th> Points Earned </th>
        </tr>
        {% for rec in users_records %}
            <tr>

                <td>{{ rec.record_date }}</td>
                <td>{{ rec.activity_num }}</td>
                <td> {{ rec.number_recorded }} </td>
                <td>{{ rec.points }}</td>

            </tr>
        {% endfor %}
    </table>
{% endblock %}