FeelGreat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('FeelGreat_main/', include('FeelGreat_main.urls')),
    path('admin/', admin.site.urls),
]

FeelGreat_main/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import views


app_name = 'FeelGreat_main'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('userrecords/<int:user_id>/', views.users_recent_records, name='users_recent_records'),
    path('progress_page/', views.progress_summary, name='progress_page'),
    path('makerecord/<int:activity_id>/', views.record_activity, name='record_activity'),
    path('record_daily_activity/', views.record_daily_activity, name='record_daily_activity'),
    path('leader_board/', views.leader_board, name='leader_board'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

FeelGreat_main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from django.views import generic

from .models import ActivityLookup, ActivityRecord, UserProfile, UnitsOfMeasure
from .utils import get_differentials, convert_to_percent, get_plot, get_point_leaders, get_weight_loss_leaders,\
    get_frequency_leaders, get_streak_leaders, cumsum
from django.contrib.auth.models import User, auth
from django.contrib import messages


# Create your views here.
class IndexView(generic.ListView):
    template_name = "FeelGreat_main/index.html"
    context_object_name = 'high_scoring_activities'

    def get_queryset(self):
        """Return All activities"""
        return ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by('-point_value')


def index(request):
    high_scoring_activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by('-point_value')
    weigh_in_activity = ActivityLookup.objects.get(activity_name="Weigh In")
    context = {'high_scoring_activities': high_scoring_activities,
               'weigh_in_activity': weigh_in_activity}
    return render(request, "FeelGreat_main/index.html", context)


def record_activity(request, activity_id):
    if request.method == "POST":
        act = ActivityLookup.objects.get(pk=activity_id)
        value = float(request.POST[act.activity_name])
        points, _ = ActivityRecord.verify_points_input(request, activity_id)
        user = request.user
        if not user.is_authenticated:
            messages.info(request, "Please sign-in or register in order to track activity.")
            return render(request, 'FeelGreat_main/register.html')
        user_prof = UserProfile.objects.filter(user_name=user.username)[0]
        record = ActivityRecord.create(new_points=points, number_recorded=value,
                                       user=user, act_num=activity_id,)
        record.save()
        return users_recent_records(request, user_prof.user_number)
    else:
        try:
            act = ActivityLookup.objects.get(pk=activity_id)
        except ActivityLookup.DoesNotExist:
            raise Http404("Activity does not exist")
        return render(request, 'FeelGreat_main/record_activity.html',
                      {'activity': act})


def users_recent_records(request, user_id):
    try:
        current_user = UserProfile.objects.get(pk=user_id)
    except UserProfile.DoesNotExist:
        raise Http404("That User does not exist. \
                       Contact administrator for more help.")
    users_records = ActivityRecord.objects.filter(user_num=user_id)
    users_records = users_records.order_by('-record_date')
    context = {'current_user': current_user, 'users_records': users_records}
    return render(request, "FeelGreat_main/users_recent_records.html", context)

def progress_summary(request):
    if request.user.is_authenticated:
        weigh_in_act = ActivityLookup.objects.get(activity_name="Weigh In")
        weigh_in_records = ActivityRecord.objects.filter(user_num=request.user.id).filter(activity_num=weigh_in_act.activity_number)
        points_records = ActivityRecord.objects.filter(user_num=request.user.id)
        print("Length of reocrds list: {}".format(len(points_records)))
        if len(points_records)==0:
            print("not enough records")
            messages.info(request, "You do not have enough activities recorded. \
                                    Keep using the app and be sure to record activity.")
            high_scoring_activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL).order_by(
                '-point_value')
            weigh_in_activity = ActivityLookup.objects.get(activity_name="Weigh In")
            context = {'high_scoring_activities': high_scoring_activities,
                       'weigh_in_activity': weigh_in_activity}
            return render(request, "FeelGreat_main/index.html", context)
        context = {}
        # make the points plot
        points_records = points_records.order_by('record_date')
        dates = [x.record_date for x in points_records]
        cum_points = [y.points for y in points_records]
        cum_points = cumsum(cum_points)
        print(dates)
        print(cum_points)
        points_plot = get_plot(dates, cum_points, plot_title="Cumulative Sum of Points",
                               y_label="Points")
        context['points_plot'] = points_plot
        print(context)
        # make the weight based plots
        if len(weigh_in_records) > 1:
            weigh_in_records = weigh_in_records.order_by('record_date')
            x = [x.record_date for x in weigh_in_records]
            y = [y.number_recorded for y in weigh_in_records]
            diffs = get_differentials(y)
            perc = convert_to_percent(y)
            diff_plot = get_plot(x, diffs, plot_title="Change in Weight",
                                 y_label="Weight Change (pounds)")
            percent_plot = get_plot(x, perc, plot_title="Percent Weight Lost",
                                    y_label="Percent of original weight")
            context['percent_plot'] = percent_plot
            context['diff_plot'] = diff_plot
        else:
            print("not enough records")
            messages.info(request, "You do not have enough Weigh In activities recorded to show weight \
                                    loss progress. Keep using the app and be sure to weigh in.")
        return render(request, "FeelGreat_main/progress_page.html", context)

    else:
        print("user was not logged in")
        messages.info(request, "You need to log in before \
                                recording and tracking activity.")
        return render(request, "FeelGreat_main/login.html")



def record_daily_activity(request):
    activities = ActivityLookup.objects.exclude(value_type=UnitsOfMeasure.WEEKLY).exclude(value_type=UnitsOfMeasure.POUNDS).exclude(value_type=UnitsOfMeasure.DAILY_SPECIAL)
    daily_act = ActivityLookup.get_daily_activity()
    checklist_activities = activities.filter(value_type=UnitsOfMeasure.DAILY)
    quantity_activities = activities.exclude(value_type=UnitsOfMeasure.DAILY)

    checklist_strings = [a.activity_name for a in checklist_activities]
    quantity_strings = [a.activity_name for a in quantity_activities]

    checklist_stuff = zip(checklist_activities, checklist_strings)
    quantity_stuff = zip(quantity_activities, quantity_strings)

    if request.method == "POST":
        if request.user.is_authenticated:
            user_prof = UserProfile.objects.get(user_number=request.user.id)
            qs_4_dailyact = ActivityLookup.objects.filter(pk=daily_act.activity_number)
            activities = activities.union(qs_4_dailyact)  # append daily act queryset
            for act in activities:
                activity_id = ActivityLookup.objects.get(activity_name=act.activity_name).activity_number
                points, value = ActivityRecord.verify_points_input(request,
                                                                   activity_id)
                if points == 0 and value == 0:
                    continue  # Fields were blank so no record needs to be made
                record = ActivityRecord.create(new_points=points,
                                               number_recorded=value,
                                               user=request.user,
                                               act_num=activity_id,)
                record.save()
            return users_recent_records(request, user_prof.user_number)
        else:
            messages.info(request, "You need to log in before \
                                    recording activity.")
            return render(request, "FeelGreat_main/login.html")
    else:
        if daily_act.activity_name == "Weigh In":
            weigh_in_bool = True
        else:
            weigh_in_bool = False
        context = {'checklist_stuff': checklist_stuff,
                   'quantity_stuff': quantity_stuff,
                   'daily_activity': daily_act,
                   'daily_activity_string': daily_act.activity_name,
                   'weigh_in': weigh_in_bool
                   }
        return render(request, "FeelGreat_main/make_daily_record.html",
                      context)


def leader_board(request):
    if request.method == 'POST':
        comparison = request.POST['comparison']
        if comparison == "points":
            leader_list = get_point_leaders()  # this shows all users
            units = "points"
        elif comparison == "weight loss":
            leader_list = get_weight_loss_leaders()
            units = "% of starting weight"
        elif comparison == "frequency":
            leader_list = get_frequency_leaders()
            units = " the number of days with records"
        elif comparison == "streak":
            leader_list = get_streak_leaders()
            units = "days in a row"
        context = {"leaders": leader_list, "title": comparison, "units": units}
        return render(request, "FeelGreat_main/leader_board.html", context)

    else:
        return render(request, "FeelGreat_main/leader_board.html")

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'home.html')
        else:
            messages.info(request, "Invalid Username or Password")
            return render(request, "FeelGreat_main/login.html")
    else:
        return render(request, "FeelGreat_main/login.html")


def logout(request):
    auth.logout(request)
    return redirect("/FeelGreat_main/login/")


def register(request):

FeelGreat_main/templates/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
    <nav>
    <ul name="navigation bar" class='topnav'>
        <li class='topnav'><a href="{% url 'FeelGreat_main:index' %}"> Activity List</a></li>
        <li class='topnav'><a href="{% url 'FeelGreat_main:leader_board' %}"> Leader Board </a></li>
        {% if user.is_authenticated %}
            <li class='topnav'><a href="{% url 'FeelGreat_main:record_daily_activity' %}">Make Daily Record</a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:users_recent_records' user.id %}"> Recent Activity </a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:progress_page' %}"> Progress </a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:home' %}"> {{user.username}} </a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:logout' %}"> Logout </a></li>
        {% else %}
            <li class='topnav'><a href="{% url 'FeelGreat_main:login' %}"> Login </a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:home' %}"> Feel Great </a></li>
            <li class='topnav'><a href="{% url 'FeelGreat_main:register' %}"> Register </a></li>
        {% endif%}
    </ul>
    </nav><br>
    <main>
        {% for mes in messages %}
            <h3> {{ mes }}</h3><br>
        {% endfor %}
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

FeelGreat_main/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h1 class="greeting"> Hi {{ user.username }}!</h1>
  {% else %}
    <p>You are not logged in. You can
    <a href="{% url 'FeelGreat_main:login' %}">Log In</a> OR
    <a href="{% url 'FeelGreat_main:register' %}"> Register New User</a>
    </p>
  {% endif %}
  <p> Welcome to my version of the Feel Great Program!</p>
  <p> This program is not necessarily about losing weight. It is more about creating and continuing healthy habits. And, maybe you will lose some weight or slim down along the way.</p>
  <h2 title="{{todays_activity.act_description}}"> The unique activity for today is: {{todays_activity.activity_name}}</h2>
  <h2 title="{{tomorrows_activity.act_description}}"> Tomorrows unique activity is: {{tomorrows_activity.activity_name}}</h2>
  <!--   {% if todays_act %}
      <h2 title="{{todays_act.act_description}}"> The unique activity for today is: {{todays_act.activity_name}}</h2>
      <h2 title="{{tomorrows_act.act_description}}"> Tomorrows unique activity is: {{tomorrows_act.activity_name}}</h2>
    {% endif %}
  -->
{% endblock %}